#!/bin/bash

pprint (){
	cred='\033[0;31m'
	cgreen='\033[0;32m'
	cyellow='\033[0;33m'
	cblue='\033[0;34m'
	cpurple='\033[0;35m'
	eval "export color='$cpurple'"
	[ ! -z "$2" ] && eval "export color=\"\$$2\""
	printf "$color $1"
}

color_reset(){ printf '\033[0;37m';}

yesnoprompt(){
	old_stty_cfg=$(stty -g)
	stty raw -echo
	answer=$(head -c 1)
	stty "$old_stty_cfg"
	echo "$answer" | grep -iq "^y"
}

update() {
	pprint "\n\nUpdating package list.. "
	sudo apt update >/dev/null 2>&1

	if [ $? -eq 0 ]; then
		pprint "DONE\n" "cgreen"
	else
		pprint "FAIL\n" "cred"
	fi
}

packages(){

	if ! command -v pip3 &>/dev/null; then
		pprint "Installing pip3... "
		sudo apt install python3-pip -y >/dev/null 2>&1 &&
		pprint "SUCCESS\n" "cgreen" ||
		(pprint "FAIL\n" "cred"; exit 1)
	fi

	if ! command -v ffmpeg &>/dev/null; then
		pprint "Installing ffmpeg... "
		sudo apt install ffmpeg -y >/dev/null 2>&1 &&
		pprint "SUCCESS\n" "cgreen" ||
		(pprint "FAIL\n" "cred"; exit 1)
	fi
}

installation(){

	pprint "\nInstalling python requirements..."

	pip3 install --upgrade pip >/dev/null 2>&1

	pip3 install -r requirements.txt &&
	pprint " DONE\n" "cgreen" &&
	return

	pprint " FAIL\n" "cred"
	exit 1
}

clear

pprint "Welcome to YousefMusic Setup Installer\n\n"

pprint "This version has Node.js installation removed.\n" "cgreen"

sleep 1

update
packages
installation

pprint "\n\nInstallation Completed Successfully!\n" "cgreen"

sleep 1
clear

pprint "\nEnter Your Values Below\n\n"

pprint "API ID: "
color_reset
read api_id

pprint "\nAPI HASH: "
color_reset
read api_hash

pprint "\nBOT TOKEN: "
color_reset
read bot_token

pprint "\nOWNER ID: "
color_reset
read ownid

pprint "\nMONGO DB URI: "
color_reset
read mongo_db

pprint "\nLOG GROUP ID: "
color_reset
read logger

pprint "\nSTRING SESSION: "
color_reset
read string_session

cat > .env << EOF
API_ID=$api_id
API_HASH=$api_hash
BOT_TOKEN=$bot_token
MONGO_DB_URI=$mongo_db
LOGGER_ID=$logger
STRING_SESSION=$string_session
OWNER_ID=$ownid
EOF

pprint "\n\nVariables saved successfully!\n" "cgreen"
pprint "\nStart bot with: python3 main.py\n\n"
